// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0hzvqVc3-BqfhauhccjgQGVXmghhOux0',
    appId: '1:493786329501:web:5533dd290300ca648fbf74',
    messagingSenderId: '493786329501',
    projectId: 'manypay-5949c',
    authDomain: 'manypay-5949c.firebaseapp.com',
    storageBucket: 'manypay-5949c.firebasestorage.app',
    measurementId: 'G-BG45T9C859',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6aQaXiQDecC4f7Dfw9Vcv4ZCfc1gbK00',
    appId: '1:493786329501:android:e14f0b50c4d56c9b8fbf74',
    messagingSenderId: '493786329501',
    projectId: 'manypay-5949c',
    storageBucket: 'manypay-5949c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOdosGrSiPtUYtPoEixZ6HZ1VjOrVGyU',
    appId: '1:493786329501:ios:24b608f95e389ab18fbf74',
    messagingSenderId: '493786329501',
    projectId: 'manypay-5949c',
    storageBucket: 'manypay-5949c.firebasestorage.app',
    iosBundleId: 'com.example.manypay',
  );
}
